<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta http-equiv="Content-Language" content="el">
        <title><?php echo $this->pageTitle; ?></title>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <?php echo $this->pageTitle; ?>
        <hr />
        <div class="content"><?php echo $this->layout()->content ?></div>
        <?php echo $this->headScript(); ?>
    </body>
</html>