<?php
// XML-related routine
$xml = new DOMDocument('1.0', 'utf-8');
$root = $xml->createElement('synedriaseis');

foreach($this->synedriaseis as $curSynedriasi) {
    $synedriasi = $xml->createElement('synedriasi');
    foreach($curSynedriasi->getOptions() as $curOption => $curValue) {
        if($curValue instanceof EDateTime && $this->timestamps == true) {
            $synedriasi->appendChild($xml->createElement($curOption, $curValue->getTimestamp()));
        } else if($curValue instanceof EDateTime && $this->iso8601 == true) {
            $synedriasi->appendChild($xml->createElement($curOption, $curValue->format('c')));
        } else if(is_scalar($curValue)) {
            $synedriasi->appendChild($xml->createElement($curOption, $curValue));
        }
    }
    $synedriasi->appendChild($xml->createElement('allDay', false));
    $synedriasi->appendChild($xml->createElement('url', htmlspecialchars($this->serverUrl().$this->url(array('id' => $curSynedriasi->get_id())))));
    $root->appendChild($synedriasi);
}

// Δημιουργία του output
$xml->appendChild($root);
echo $xml->saveXML();
?>